### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by EAkita** [UTNuclearRoboticsPublic/rviz_openhmd#10]
Hey,
Im trying to run it and it crashes with core dump right after im loading the plugin.
Any idea f what might be the reason?
I'm using melodic with ubuntu 18.04
The output is:
`num devices: 5
vendor: HTC/Valve
product: HTC Vive
path: 0
vendor: OpenHMD
product: External Device
path: (none)
vendor: OpenHMD
product: HMD Null Device
path: (none)
vendor: OpenHMD
product: Left Controller Null Device
path: (none)
vendor: OpenHMD
product: Right Controller Null Device
path: (none)
[II] 0bb4:2c87 0003:0019:00

[II] opening

[II] 28de:2000 0003:001c:00

[II] opening

[II] 28de:2000 0003:001c:01

[II] manufacturer: 'HTC'

[II] product: 'HTC Vive'

[II] serial number: '207039554241'

[II] power on magic: 64

[II] Getting feature report 16 to 39

got 64 bytes
10 0d b7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

[II] 
--- Converted Vive JSON Data ---

[II] acc_bias = 0.270300 -0.000568 0.011410

[II] acc_scale = 1.000000 0.999000 0.994900

[II] gyro_bias = 0.005057 -0.001804 -0.032920

[II] gyro_scale = 1.000000 1.000000 1.000000

[II] 
--- End of Vive JSON Data ---

[II] gyro_range 8.726646

[II] acc_range 39.226600

[EE] unknown message type: 0
[EE] gyro error: -0.023327, 0.005119, 0.004079
FileSystem
../catkin_ws/src/rviz_openhmd/src/resources/
Render window created
Cameras Created
Cameras positioned
Viewports added to window
HMD generic
Enabling compositors
Segmentation fault (core dumped)
`

**Comment by gzaidner** [comment]
Solved. It was a problem of missing dependencies
