### ISSUE TITLE
OpenHMD_Includes not found

### ISSUE THREAD

**Issue by AndyZe** [UTNuclearRoboticsPublic/rviz_openhmd#4]
I encounter this on trying to build for the first time. I did clone & build OpenHMD per the instructions there.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OpenHMD_INCLUDES
```

**Comment by btandersen383** [comment]
This is an issue located in the CMakeLists.txt file. Check that line 42 contains the path to where you have installed OpenHMD. We are looking into providing precompiled .so and the .h so this will no longer need to be modified. Updates coming this week.

As it is now, we expect you to download, compile, and install OpenHMD yourself. The process can be kind of tedious so we hope to remove these steps for users.

**Comment by AndyZe** [comment]
Thanks!
