### ISSUE TITLE
How to change focal point in rviz

### ISSUE THREAD

**Issue by akashjinandra** [UTNuclearRoboticsPublic/rviz_openhmd#5]
Hello,

I really appreciate what you have made here. So far I've been able to get everything to run with your instructions and I'm able to open up rviz and view my robot. But it seems as though my view point is at 0,0,0 in the viewer. I'm wondering if it's possible to change the perspective of the headset  so I'm not in the center, I know it's possible to drag around the view that is displayed into the headset if that makes sense. Please feel free to ask any questions.

**Comment by btandersen383** [comment]
Are you asking about the position of the virtual cameras that provide your point of view within the 3D OGRE space? You can look to line 158 in src/openhmd__display.cpp and see the `mCamera->setPosition()` to determine the position of the cameras in the 3D space. You can then change the orientation on the line just below. It is not made to be changed during run time right now.

**Comment by akashjinandra** [comment]
Thanks for the udpate. Yes, that's what I'm talking about, is it possible to tie this to the rviz moveable camera? After changing this number, it doesn't seem to have moved me in my world at all. Is it in the same axis an scale? X,Y,Z and in Meters?

**Comment by btandersen383** [comment]
It may be possible to attach the stereo cameras created for each 'eye' of the headset to the camera object you are referring to instead of to the scene node created in the plugin. This should cause the camera objects to follow that node. However, I would not know how to go about getting access to the object you have in mind.

**Comment by akashjinandra** [comment]
@AndyZe Is this an issue you are trying to address by adding in the position of the headset given by the lighthouse trackers? Also how are you able to pair the headset to the lighthouse without SteamVR?

**Comment by AndyZe** [comment]
I'm looking at a way for rviz_openhmd to listen to ROS TF, which would set the headset position (in ROS and in RViz). Orientation would still come from the headset IMU.

No, I didn't get the lighthouse trackers working concurrently with rviz_openhmd.

**Comment by AndyZe** [comment]
@akashjinandra The branch _headset_pose_from_ros_tf_ listens for a tf frame called `hmd` and places the camera there. I believe this will achieve what you want.

It doesn't do anything for orientation -- orientation of the view is still established by the headset IMU.
